"""add-class-users

Revision ID: 083d19fefd3a
Revises: c961b04df0cc
Create Date: 2026-07-09 08:00:19.513150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083d19fefd3a'
down_revision: Union[str, Sequence[str], None] = 'c961b04df0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column("workout", sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_workout_user_id_app_users", 'workout', 'app_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_workout_user_id_app_users", 'workout', type_='foreignkey')
    op.drop_column('workout', 'user_id')
    op.drop_table('app_users')
    # ### end Alembic commands ###
