"""add workout completion

Revision ID: 7eaaf6c63524
Revises: 8d0f8814e171
Create Date: 2026-07-19 18:41:58.164185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eaaf6c63524'
down_revision: Union[str, Sequence[str], None] = '8d0f8814e171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'completed_at')
    # ### end Alembic commands ###
