"""add effort level

Revision ID: 8d0f8814e171
Revises: 083d19fefd3a
Create Date: 2026-07-18 19:43:07.175120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0f8814e171'
down_revision: Union[str, Sequence[str], None] = '083d19fefd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('effort_level', sa.VARCHAR(length=16), nullable=True))
    op.create_check_constraint(
        "check_workout_effort_level",
        "workout",
        "effort_level IS NULL OR "
        "effort_level IN ('light', 'moderate', 'hard', 'very_hard')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_workout_effort_level",
        "workout",
        type_="check",
    )
    op.drop_column('workout', 'effort_level')
    # ### end Alembic commands ###
